# -*- coding: utf-8 -*-
"""
全国高校毕业生秋招/提前批全行业名企真实校招日程权威知识库
涵盖医疗健康/生物医药、智能制造/汽车芯片、央国企/科研院所、金融科技/商业银行、互联网/IT软件与综合消费品龙头。
"""

from typing import List, Dict, Any

AUTHORITATIVE_CAMPUS_RECRUITS: List[Dict[str, Any]] = [
    # ==================== 1. 医疗健康 / 生物医药 / 医疗器械 ====================
    {
        "company_name": "艾昆纬 (IQVIA)",
        "industry": "医疗健康/生物医药",
        "recruitment_type": "秋招正式批 (临床运营与医学)",
        "target_graduates": "2026/2027届",
        "roles_summary": "临床研究副监查员 (CRA Trainee)、临床研究协调员 (CRC)、临床试验助理 (CTA)、药物安全与警戒专员 (PV)、临床质量合规专员 (QA) (地点: 上海/北京/广州/成都/武汉/长沙/全国核心城市)",
        "apply_url": "https://jobs.iqvia.com/zh-CN",
        "referral_code": "IQVIA2026VIP",
        "start_date": "2026-09-01",
        "deadline": "2026-11-30",
        "status": "hot",
        "source": "艾昆纬中国官方校园招聘",
        "announcement_text": "全球第一大临床试验外包(CRO)与医疗大数据巨头。提供全球权威 ICH-GCP 规范体系化实战培训、全额顶格公积金12%、覆盖配偶与子女的高额补充商业医保、15天超长带薪年假与清晰的 CRA/CRC 双轨晋升通道。"
    },
    {
        "company_name": "艾昆纬 (IQVIA)",
        "industry": "医疗健康/生物医药",
        "recruitment_type": "秋招正式批 (数理统计与数据科学)",
        "target_graduates": "2026/2027届",
        "roles_summary": "生物统计师 (Biostatistician)、SAS统计程序员 (Statistical Programmer)、临床数据管理员 (Data Management/CDM)、医学编码专员 (Medical Coder) (地点: 上海/大连/北京/全国支持远程)",
        "apply_url": "https://jobs.iqvia.com/zh-CN",
        "referral_code": "IQVIA2026VIP",
        "start_date": "2026-09-01",
        "deadline": "2026-11-30",
        "status": "hot",
        "source": "艾昆纬全球统计与数据中心",
        "announcement_text": "艾昆纬统计与数据科学中心是全球医药研发的数理中枢。负责全球多中心大型临床试验的统计方案设计、SAP 撰写、CDISC 标准转换与 FDA/NMPA 申报数据分析，技术积淀深厚。"
    },
    {
        "company_name": "艾昆纬 (IQVIA)",
        "industry": "医疗健康/生物医药",
        "recruitment_type": "秋招正式批 (商业咨询与真实世界研究)",
        "target_graduates": "2026/2027届",
        "roles_summary": "医药管理咨询分析师 (Consulting Analyst)、真实世界研究分析师 (RWE Analyst)、卫生经济与结果研究顾问 (HEOR Consultant)、医药市场研究顾问 (地点: 上海/北京)",
        "apply_url": "https://jobs.iqvia.com/zh-CN",
        "referral_code": "IQVIA2026VIP",
        "start_date": "2026-09-01",
        "deadline": "2026-11-30",
        "status": "hot",
        "source": "艾昆纬中国咨询与战略洞察中心",
        "announcement_text": "全球顶尖医药商业咨询智库，为全球跨国药企、创新药独角兽及政府医保部门提供新药上市定价、市场准入准则、医院销售预测与卫生经济学评估支持。"
    },
    {
        "company_name": "艾昆纬 (IQVIA)",
        "industry": "医疗健康/生物医药",
        "recruitment_type": "秋招正式批 (医疗科技与信息数字化)",
        "target_graduates": "2026/2027届",
        "roles_summary": "医药大数据开发工程师 (Big Data Engineer)、医疗软件研发工程师 (Java/Python)、数字化系统实施顾问、AI医学算法工程师 (地点: 上海/北京/大连)",
        "apply_url": "https://jobs.iqvia.com/zh-CN",
        "referral_code": "IQVIA2026VIP",
        "start_date": "2026-09-01",
        "deadline": "2026-11-30",
        "status": "hot",
        "source": "艾昆纬科技与数字化解决方案事业部",
        "announcement_text": "致力于运用人工智能、云计算与医疗大数据底座赋能智慧医疗与临床试验数字化管理。"
    },
    {
        "company_name": "艾昆纬 (IQVIA)",
        "industry": "医疗健康/生物医药",
        "recruitment_type": "日常/暑期实习生",
        "target_graduates": "2026/2027届",
        "roles_summary": "临床运营实习生 (CRA Intern)、生物统计编程实习生 (SAS Intern)、医药咨询研究实习生、医学信息实习生 (地点: 上海/北京/全国重点城市医院项目组，表现优异提供转正Offer)",
        "apply_url": "https://jobs.iqvia.com/zh-CN",
        "referral_code": "IQVIA2026VIP",
        "start_date": "2026-09-01",
        "deadline": "2026-12-31",
        "status": "hot",
        "source": "艾昆纬中国人才实习生孵化计划",
        "announcement_text": "针对在校本科生与研究生的快速实战通道，导师一对一带教，直面国际顶级药企多中心临床真实项目。"
    },
    {
        "company_name": "泰格医药 (Tigermed)",
        "industry": "医疗健康/生物医药",
        "recruitment_type": "秋招正式批 (临床监查与运营中心)",
        "target_graduates": "2026/2027届",
        "roles_summary": "临床监查员 (CRA Trainee)、临床研究协调员 (CRC)、临床试验项目助理 (CTA)、受试者招募专员、质量保证专员 (QA) (地点: 杭州/上海/北京/广州/成都/全国100+核心医院网点)",
        "apply_url": "https://www.tigermed.net/career",
        "referral_code": "TG2026CAMPUS",
        "start_date": "2026-09-01",
        "deadline": "2026-11-20",
        "status": "hot",
        "source": "泰格医药校园招聘官网",
        "announcement_text": "中国临床合同研究(CRO)领军上市企业。为毕业生打造临床试验双通道快速晋升通道，导师制实战带教，出差与交通补贴健全。"
    },
    {
        "company_name": "泰格医药 (Tigermed)",
        "industry": "医疗健康/生物医药",
        "recruitment_type": "秋招正式批 (数理统计与数据科学)",
        "target_graduates": "2026/2027届",
        "roles_summary": "生物统计师 (Biostatistician)、SAS统计程序员 (Statistical Programmer)、临床数据管理员 (CDM)、医学编写员 (Medical Writer) (地点: 杭州/上海/北京/大连/武汉)",
        "apply_url": "https://www.tigermed.net/career",
        "referral_code": "TG2026CAMPUS",
        "start_date": "2026-09-01",
        "deadline": "2026-11-20",
        "status": "hot",
        "source": "泰格医药数理与统计中心",
        "announcement_text": "国内规模最大的临床数据科学与统计团队之一，负责数十个创新药注册上市申报的数理分析与递交支持。"
    },
    {
        "company_name": "迈瑞医疗 (Mindray)",
        "industry": "医疗健康/生物医药",
        "recruitment_type": "秋招正式批 (研发与技术创新专场)",
        "target_graduates": "2026/2027届",
        "roles_summary": "超声算法研究员、生命信息研发工程师、体外诊断(IVD)化学与试剂研发、嵌入式软件开发、高精度硬件与机械结构 (地点: 深圳/北京/南京/西安/武汉)",
        "apply_url": "https://career.mindray.com/campus",
        "referral_code": "MR2026VIP",
        "start_date": "2026-09-01",
        "deadline": "2026-10-31",
        "status": "hot",
        "source": "迈瑞医疗官方招聘系统",
        "announcement_text": "全球领先的医疗器械与解决方案供应商。研发投入占比超10%，设立极具行业竞争力的薪酬、全额五险一金及专项免息安家贷款。"
    },
    {
        "company_name": "迈瑞医疗 (Mindray)",
        "industry": "医疗健康/生物医药",
        "recruitment_type": "秋招正式批 (临床应用与全球营销专场)",
        "target_graduates": "2026/2027届",
        "roles_summary": "临床应用专家 (超声/麻醉/重症)、海外技术支持工程师、国内营销管培生、全球供应链工程师 (地点: 深圳/全国各分公司及海外各大区)",
        "apply_url": "https://career.mindray.com/campus",
        "referral_code": "MR2026VIP",
        "start_date": "2026-09-01",
        "deadline": "2026-10-31",
        "status": "hot",
        "source": "迈瑞医疗全球营销中心",
        "announcement_text": "面向临床医学、生物医学工程及外语商科优秀毕业生的全球化职业舞台，提供全方位轮岗培养。"
    },
    {
        "company_name": "江苏恒瑞医药",
        "industry": "医疗健康/生物医药",
        "recruitment_type": "秋招正式批",
        "target_graduates": "2026/2027届",
        "roles_summary": "创新药研发科学家、临床研究员(CRA/CRC)、医学联络官(MSL)、制剂研究员、生物分析 (地点: 上海/连云港/南京/成都)",
        "apply_url": "https://hr.hengrui.com/campus",
        "referral_code": "HR_MED_2026",
        "start_date": "2026-09-01",
        "deadline": "2026-10-25",
        "status": "hot",
        "source": "恒瑞医药全球校园招聘官网",
        "announcement_text": "国内创新药标杆龙头企业。建有国家级企业技术中心，为应届硕博毕业生提供专属科研启动津贴与导师一对一培养带教。"
    },
    {
        "company_name": "联影医疗 (United Imaging)",
        "industry": "医疗健康/生物医药",
        "recruitment_type": "秋招提前批 (核心算法与人工智能专场)",
        "target_graduates": "2026/2027届",
        "roles_summary": "高端医学影像重构算法(CT/MR/PET-CT)、深度学习医学图像分割、多模态智能辅助诊断算法研究员 (地点: 上海/武汉/北京)",
        "apply_url": "https://career.united-imaging.com/",
        "referral_code": "UIH_TALENT888",
        "start_date": "2026-08-20",
        "deadline": "2026-09-20",
        "status": "ending",
        "source": "联影医疗人工智能研究院",
        "announcement_text": "全线覆盖高端医学影像诊断和治疗系统的独角兽跨国企业。提供落户重点扶持、高端人才公寓与专项研发奖金池。"
    },
    {
        "company_name": "联影医疗 (United Imaging)",
        "industry": "医疗健康/生物医药",
        "recruitment_type": "秋招正式批 (系统工程与软硬件研发)",
        "target_graduates": "2026/2027届",
        "roles_summary": "底层驱动与嵌入式软件系统、射频/高压硬件开发、精密机械结构、医疗系统电气控制 (地点: 上海/武汉/常州)",
        "apply_url": "https://career.united-imaging.com/",
        "referral_code": "UIH_TALENT888",
        "start_date": "2026-09-01",
        "deadline": "2026-11-15",
        "status": "hot",
        "source": "联影医疗系统工程中心",
        "announcement_text": "打造自主可控的高端大型医疗装备核心硬科技，享有高精尖科研攻坚环境与全方位福利保障。"
    },
    {
        "company_name": "药明康德 (WuXi AppTec)",
        "industry": "医疗健康/生物医药",
        "recruitment_type": "秋招正式批",
        "target_graduates": "2026/2027届",
        "roles_summary": "有机合成研究员、药物化学、分析化学、生物学研究员、临床协调、毒理药理评价 (地点: 上海/武汉/天津/苏州/成都)",
        "apply_url": "https://wuxiapptec.zhiye.com/",
        "referral_code": "WX2026CAREER",
        "start_date": "2026-09-05",
        "deadline": "2026-11-15",
        "status": "hot",
        "source": "药明康德全球招聘官网",
        "announcement_text": "国际领先的医药研发与生产开放式平台。涵盖化学药物、细胞基因疗法与医疗器械测试，拥有全球化轮岗通道。"
    },
    {
        "company_name": "百济神州 (BeiGene)",
        "industry": "医疗健康/生物医药",
        "recruitment_type": "秋招正式批",
        "target_graduates": "2026/2027届",
        "roles_summary": "肿瘤免疫研究、抗体工程、生物统计师、临床医学事务(MA)、全球临床运营技术专家 (地点: 北京/上海/广州)",
        "apply_url": "https://www.beigene.com.cn/careers/",
        "referral_code": "BEIGENE2026",
        "start_date": "2026-09-08",
        "deadline": "2026-11-20",
        "status": "hot",
        "source": "百济神州全球招聘官网",
        "announcement_text": "首家在美国纳斯达克、香港联交所与上交所三地上市的全球化肿瘤创新药先锋企业，提供国际化科研视野与双通道职业发展。"
    },
    {
        "company_name": "华大基因 (BGI)",
        "industry": "医疗健康/生物医药",
        "recruitment_type": "秋招正式批",
        "target_graduates": "2026/2027届",
        "roles_summary": "基因组学生物信息分析、分子生物学实验研究员、测序算法开发、精准医疗产品经理 (地点: 深圳/武汉/北京/杭州)",
        "apply_url": "https://bgi.hotjob.cn/",
        "referral_code": "BGI_GENOME26",
        "start_date": "2026-09-01",
        "deadline": "2026-10-30",
        "status": "hot",
        "source": "华大基因校园招聘系统",
        "announcement_text": "全球领先的生命科学前沿机构。依托国家基因库与全球测序平台，致力于生命科学与精准医学普惠大众。"
    },
    {
        "company_name": "阿斯利康中国 (AstraZeneca)",
        "industry": "医疗健康/生物医药",
        "recruitment_type": "秋招正式批",
        "target_graduates": "2026/2027届",
        "roles_summary": "医学信息顾问、临床试验项目管理、数字医疗创新产品经理、卫生经济学与准入评价 (地点: 上海/北京/广州/各省会)",
        "apply_url": "https://careers.astrazeneca.com/china",
        "referral_code": "AZ_CHINA_VIP888",
        "start_date": "2026-09-01",
        "deadline": "2026-10-15",
        "status": "hot",
        "source": "阿斯利康中国招聘门户",
        "announcement_text": "全球领先的制药创新跨国企业。深耕心血管、肿瘤、呼吸及罕见病领域，为高校应届生提供完善的全球管培培养梯队。"
    },

    # ==================== 2. 智能制造 / 汽车芯片 / 硬科技 ====================
    {
        "company_name": "华为技术有限公司 (Huawei)",
        "industry": "智能制造/汽车芯片",
        "recruitment_type": "秋招正式批 (通用软件与芯片系统)",
        "target_graduates": "2026/2027届",
        "roles_summary": "芯片架构与验证(海思)、通信基带算法、鸿蒙OS开发、编译器与编程语言、网络安全 (地点: 深圳/上海/北京/西安/成都/武汉)",
        "apply_url": "https://career.huawei.com/reccampps/",
        "referral_code": "HW2026CAMPUS",
        "start_date": "2026-08-25",
        "deadline": "2026-10-31",
        "status": "hot",
        "source": "华为校园招聘官方平台",
        "announcement_text": "全球领先的ICT基础设施和智能终端提供商。提供世界级研发挑战平台、行业领先薪酬与顶级科学家导师带教计划。"
    },
    {
        "company_name": "华为技术有限公司 (Huawei)",
        "industry": "智能制造/汽车芯片",
        "recruitment_type": "秋招正式批 (AI与智能汽车解决方案)",
        "target_graduates": "2026/2027届",
        "roles_summary": "华为车BU智能驾驶感知算法、高精度规划决策、昇腾AI计算框架、智能座舱交互算法 (地点: 深圳/上海/北京/苏州)",
        "apply_url": "https://career.huawei.com/reccampps/",
        "referral_code": "HW2026CAMPUS",
        "start_date": "2026-08-25",
        "deadline": "2026-10-31",
        "status": "hot",
        "source": "华为智能汽车解决方案与AI计算中心",
        "announcement_text": "聚焦下一代智能网联电动车与全栈AI计算平台研发，提供行业顶尖实战课题与顶格年薪包。"
    },
    {
        "company_name": "比亚迪股份有限公司 (BYD)",
        "industry": "智能制造/汽车芯片",
        "recruitment_type": "秋招正式批 (三电核心与新能源工程)",
        "target_graduates": "2026/2027届",
        "roles_summary": "新能源整车控制、刀片电池研发、电机电控系统、整车热管理与底盘调校、整车制造工程 (地点: 深圳/西安/长沙/常州/郑州)",
        "apply_url": "https://job.byd.com/campus",
        "referral_code": "BYD_AUTO_2026",
        "start_date": "2026-08-30",
        "deadline": "2026-11-30",
        "status": "hot",
        "source": "比亚迪招聘官网",
        "announcement_text": "全球新能源汽车与动力电池龙头。拥有全产业链核心研发制造实力，为优秀应届生提供定制化落户奖励与购车免息支持。"
    },
    {
        "company_name": "比亚迪股份有限公司 (BYD)",
        "industry": "智能制造/汽车芯片",
        "recruitment_type": "秋招正式批 (智能网联与汽车软件)",
        "target_graduates": "2026/2027届",
        "roles_summary": "自动驾驶感知与决策算法、智能座舱软件开发(Android/Linux)、汽车电子与车规半导体研发 (地点: 深圳/上海/西安)",
        "apply_url": "https://job.byd.com/campus",
        "referral_code": "BYD_AUTO_2026",
        "start_date": "2026-08-30",
        "deadline": "2026-11-30",
        "status": "hot",
        "source": "比亚迪智能化与软件研发中心",
        "announcement_text": "万亿级汽车巨头全面发力智能化下半场，招募全球顶尖汽车软件与算法应届英才。"
    },
    {
        "company_name": "大疆创新 (DJI)",
        "industry": "智能制造/汽车芯片",
        "recruitment_type": "秋招提前批",
        "target_graduates": "2026/2027届",
        "roles_summary": "飞行控制算法、机器视觉与空间智能、云台增稳、电机控制、嵌入式底层系统 (地点: 深圳/上海)",
        "apply_url": "https://we.dji.com/campus",
        "referral_code": "DJI_DRONE2026",
        "start_date": "2026-08-15",
        "deadline": "2026-09-19",
        "status": "ending",
        "source": "大疆创新校园招聘系统",
        "announcement_text": "全球无人机与手持影像系统独角兽领跑者。工程师文化浓厚，提供高标准创新研发环境与专属应届生极客公寓。"
    },
    {
        "company_name": "宁德时代 (CATL)",
        "industry": "智能制造/汽车芯片",
        "recruitment_type": "秋招正式批 (21C创新实验室与前瞻材料)",
        "target_graduates": "2026/2027届",
        "roles_summary": "固态电池前沿研究、电芯电化学设计、先进材料仿真与机理研究、计算化学研究员 (地点: 宁德/厦门/上海)",
        "apply_url": "https://talent.catl.com/campus",
        "referral_code": "CATL_BATTERY26",
        "start_date": "2026-09-01",
        "deadline": "2026-10-31",
        "status": "hot",
        "source": "宁德时代全球招聘官网",
        "announcement_text": "全球领先的动力电池和储能电池超级独角兽。建有21C创新实验室，提供全方位员工关爱基金与股权激励机制。"
    },
    {
        "company_name": "宁德时代 (CATL)",
        "industry": "智能制造/汽车芯片",
        "recruitment_type": "秋招正式批 (极限制造与精益工程)",
        "target_graduates": "2026/2027届",
        "roles_summary": "极速自动化产线研发、工业机器视觉质检算法、智能电池管理系统(BMS)、数字孪生系统工程 (地点: 宁德/宜宾/常州/海外基地)",
        "apply_url": "https://talent.catl.com/campus",
        "referral_code": "CATL_BATTERY26",
        "start_date": "2026-09-01",
        "deadline": "2026-10-31",
        "status": "hot",
        "source": "宁德时代极限制造工程中心",
        "announcement_text": "打造全球首屈一指的动力电池灯塔工厂，享有业内顶尖工程实践与海外派驻机会。"
    },
    {
        "company_name": "中芯国际 (SMIC)",
        "industry": "智能制造/汽车芯片",
        "recruitment_type": "秋招正式批",
        "target_graduates": "2026/2027届",
        "roles_summary": "集成电路先进制程研发、晶圆制造工艺整合(PIE)、光刻/刻蚀技术专家、器件物理 (地点: 上海/北京/天津/深圳)",
        "apply_url": "https://careers.smics.com/campus",
        "referral_code": "SMIC_CHIP2026",
        "start_date": "2026-09-01",
        "deadline": "2026-11-20",
        "status": "hot",
        "source": "中芯国际招聘网",
        "announcement_text": "国内规模最大、技术最先进的集成电路晶圆代工企业。承担国家芯战略重任，落户指标充足，配套专项芯片人才公寓。"
    },
    {
        "company_name": "海康威视 (HIKVISION)",
        "industry": "智能制造/汽车芯片",
        "recruitment_type": "秋招正式批",
        "target_graduates": "2026/2027届",
        "roles_summary": "多模态感知算法、物联传感器研发、嵌入式软件、热成像技术、智慧工业视觉 (地点: 杭州/西安/武汉/成都)",
        "apply_url": "https://campushr.hikvision.com/",
        "referral_code": "HIK_VISION2026",
        "start_date": "2026-08-28",
        "deadline": "2026-10-28",
        "status": "hot",
        "source": "海康威视校园招聘官网",
        "announcement_text": "专注物联智能与感知技术的智能制造龙头企业。建有全球五大研发基地，提供行业内高标准的员工跟投与年金保障。"
    },
    {
        "company_name": "蔚来汽车 (NIO)",
        "industry": "智能制造/汽车芯片",
        "recruitment_type": "秋招正式批",
        "target_graduates": "2026/2027届",
        "roles_summary": "智能底盘开发、电驱高压电控、智能座舱AI大模型、换电站系统工程 (地点: 上海/合肥/北京/武汉)",
        "apply_url": "https://nio.jobs.feishu.cn/campus",
        "referral_code": "NIO_AUTO2026",
        "start_date": "2026-09-01",
        "deadline": "2026-10-31",
        "status": "hot",
        "source": "蔚来招聘官网",
        "announcement_text": "全球化智能电动汽车品牌。研发团队遍布全球，注重前沿技术自研创新与年轻工程师的跨国项目实践。"
    },

    # ==================== 3. 央企国企 / 科研院所 ====================
    {
        "company_name": "国家电网有限公司 (State Grid)",
        "industry": "央国企/科研院所",
        "recruitment_type": "秋招正式批",
        "target_graduates": "2026/2027届",
        "roles_summary": "电气工程、电力系统自动化、智能电网调控、南瑞/智芯微电子数字化研发、综合管理 (地点: 全国各省网公司)",
        "apply_url": "https://zhaopin.sgcc.com.cn/",
        "referral_code": "SGCC_OFFICIAL",
        "start_date": "2026-09-10",
        "deadline": "2026-11-20",
        "status": "hot",
        "source": "国家电网人力资源招聘平台",
        "announcement_text": "世界500强特大型中央骨干企业。组织统一全国统考笔试，解决落户指标、提供七险二金与完善的终身专业发展通道。"
    },
    {
        "company_name": "中国移动通信集团 (China Mobile)",
        "industry": "央国企/科研院所",
        "recruitment_type": "秋招正式批",
        "target_graduates": "2026/2027届",
        "roles_summary": "5G/6G移动通信、移动云架构师、AI算法研究员(九天大模型)、物联网技术、网络安全 (地点: 全国各省分公司/直属院所)",
        "apply_url": "https://job.10086.cn/",
        "referral_code": "CMCC_CAMPUS26",
        "start_date": "2026-09-05",
        "deadline": "2026-10-25",
        "status": "hot",
        "source": "中国移动招聘门户",
        "announcement_text": "全球网络规模与客户规模最大的通信运营商。全面向算力网络与数智服务转型，为应届生提供雄厚的科研资源支撑。"
    },
    {
        "company_name": "中国电信集团 (China Telecom)",
        "industry": "央国企/科研院所",
        "recruitment_type": "秋招正式批",
        "target_graduates": "2026/2027届",
        "roles_summary": "天翼云分布式存储、视联网技术、量子保密通信、算力网络调度、政企数字化解决方案 (地点: 全国)",
        "apply_url": "http://job.chinatelecom.com.cn/",
        "referral_code": "TELECOM2026",
        "start_date": "2026-09-08",
        "deadline": "2026-10-31",
        "status": "hot",
        "source": "中国电信集团招聘官网",
        "announcement_text": "领先的综合智能信息服务运营商。天翼云在全球算力与政企云领域占据核心地位，提供全方位落户保障与导师培养。"
    },
    {
        "company_name": "中国核工业集团 (CNNC)",
        "industry": "央国企/科研院所",
        "recruitment_type": "秋招正式批",
        "target_graduates": "2026/2027届",
        "roles_summary": "核能与核工程、反应堆热工水力、核燃料循环、辐射防护、大型核电站电气运行与控制 (地点: 北京/上海/武汉/核电基地)",
        "apply_url": "https://cnnc.zhiye.com/",
        "referral_code": "CNNC_NUCLEAR26",
        "start_date": "2026-09-01",
        "deadline": "2026-11-10",
        "status": "hot",
        "source": "中核集团校园招聘平台",
        "announcement_text": "国家核科技工业主力军。承担大国重器科研任务，提供国防军工专项科研津贴、优厚福利与系统性国防英才工程。"
    },
    {
        "company_name": "中国航天科工集团 (CASIC)",
        "industry": "央国企/科研院所",
        "recruitment_type": "秋招正式批",
        "target_graduates": "2026/2027届",
        "roles_summary": "飞行器设计、制导与控制、雷达信号处理、航天微电子、复杂航天系统仿真与总体技术 (地点: 北京/武汉/西安/成都)",
        "apply_url": "http://www.casic.com.cn/n103/index.html",
        "referral_code": "CASIC_AERO2026",
        "start_date": "2026-09-01",
        "deadline": "2026-11-15",
        "status": "hot",
        "source": "航天科工人才招聘平台",
        "announcement_text": "战略性高科技特大型军工央企。建有多个国家级重点实验室，提供中央在京落户指标、事业编制通道与安居保障。"
    },

    # ==================== 4. 金融科技 / 商业银行 / 证券 ====================
    {
        "company_name": "招商银行总行 (China Merchants Bank)",
        "industry": "金融/银行",
        "recruitment_type": "秋招正式批",
        "target_graduates": "2026/2027届",
        "roles_summary": "总行金融科技生(FinTech管培)、投行与金融市场、资产管理研究员、数据智能算法、财富管理 (地点: 深圳/上海/北京)",
        "apply_url": "https://career.cmbchina.com/",
        "referral_code": "CMB_FINTECH26",
        "start_date": "2026-08-28",
        "deadline": "2026-10-20",
        "status": "hot",
        "source": "招商银行官方招聘系统",
        "announcement_text": "国内零售与财富管理第一行。金融科技年投入超百亿，设立大模型应用创新实验室，提供行业领先的薪酬福利待遇。"
    },
    {
        "company_name": "蚂蚁集团 (Ant Group)",
        "industry": "金融/银行",
        "recruitment_type": "秋招正式批",
        "target_graduates": "2026/2027届",
        "roles_summary": "大规模分布式高并发架构、金融级安全风控AI、图计算与区块链、智能投顾算法 (地点: 杭州/北京/上海/深圳)",
        "apply_url": "https://talent.antgroup.com/campus",
        "referral_code": "ANT_AI_VIP2026",
        "start_date": "2026-09-01",
        "deadline": "2026-10-31",
        "status": "hot",
        "source": "蚂蚁集团校园招聘官网",
        "announcement_text": "全球领先的金融科技开放平台。旗下拥有支付宝、数字科技等核心业务，技术氛围极佳，提供丰厚安居房补与无息贷款。"
    },
    {
        "company_name": "中国银行软件中心 (BOC Software)",
        "industry": "金融/银行",
        "recruitment_type": "秋招正式批",
        "target_graduates": "2026/2027届",
        "roles_summary": "全球化核心银行系统研发、云原生金融架构、跨境金融科技、区块链支付、信息安全 (地点: 北京/西安/深圳/合肥)",
        "apply_url": "https://campus.chinahr.com/pages/boc/",
        "referral_code": "BOC_SOFT_2026",
        "start_date": "2026-09-01",
        "deadline": "2026-10-18",
        "status": "hot",
        "source": "中国银行校园招聘官网",
        "announcement_text": "全球化与综合化程度最高的国有大型商业银行软件直属机构，享受北京等地重点落户指标，工作氛围规范稳定。"
    },
    {
        "company_name": "中信证券股份有限公司 (CITIC Securities)",
        "industry": "金融/银行",
        "recruitment_type": "秋招正式批",
        "target_graduates": "2026/2027届",
        "roles_summary": "投资银行部(IPO/并购)、固收及衍生品量化交易、行业研究员、金融工程算法、财富配置顾问 (地点: 北京/上海/深圳)",
        "apply_url": "https://customer.citics.com/campus",
        "referral_code": "CITIC_SEC2026",
        "start_date": "2026-09-02",
        "deadline": "2026-10-31",
        "status": "hot",
        "source": "中信证券人才招聘平台",
        "announcement_text": "国内综合实力与业务收入多年稳居第一的券商龙头。拥有全球化资本市场运作平台，为应届生提供高成长薪资与顶级投行实战经验。"
    },

    # ==================== 5. 互联网 / IT 软件大厂 ====================
    {
        "company_name": "腾讯控股 (Tencent)",
        "industry": "互联网/IT",
        "recruitment_type": "秋招正式批 (技术研发与AI大模型专场)",
        "target_graduates": "2026/2027届",
        "roles_summary": "混元大模型多模态算法、微信核心架构、腾讯云分布式底座、游戏引擎底层研发、后台开发(C++/Go)、网络安全与编译器 (地点: 深圳/北京/上海/广州/成都)",
        "apply_url": "https://join.qq.com/",
        "referral_code": "TENCENT2026VIP",
        "start_date": "2026-08-25",
        "deadline": "2026-10-31",
        "status": "hot",
        "source": "腾讯招聘官网 (技术专场)",
        "announcement_text": "全球领先的互联网科技公司。用户为本科技向善，混元AI大模型与微信技术底座全面开放校招，提供行业顶薪、免息房贷与双通道晋升。"
    },
    {
        "company_name": "腾讯控股 (Tencent)",
        "industry": "互联网/IT",
        "recruitment_type": "秋招正式批 (产品策划、运营与商业化)",
        "target_graduates": "2026/2027届",
        "roles_summary": "产品经理培训生(产培生)、微信生态商业化运营、游戏数值与发行策划、海外业务拓展、数据战略分析师 (地点: 深圳/广州/北京/上海)",
        "apply_url": "https://join.qq.com/",
        "referral_code": "TENCENT2026VIP",
        "start_date": "2026-08-25",
        "deadline": "2026-10-31",
        "status": "hot",
        "source": "腾讯招聘官网 (非技术专场)",
        "announcement_text": "腾讯产培生与业务核心团队全面纳新，由业务高管亲自导师带教，深度参与亿级DAU产品设计与全球化商业拓展。"
    },
    {
        "company_name": "阿里巴巴集团 (Alibaba)",
        "industry": "互联网/IT",
        "recruitment_type": "秋招正式批 (云计算与通义大模型专项)",
        "target_graduates": "2026/2027届",
        "roles_summary": "通义千问基础大模型研发、阿里云分布式操作系统、大规模智算平台Infra、智能云存储与网络、异构计算硬件 (地点: 杭州/北京/上海/深圳)",
        "apply_url": "https://talent.alibaba.com/campus",
        "referral_code": "ALI_CAMPUS2026",
        "start_date": "2026-08-28",
        "deadline": "2026-10-31",
        "status": "hot",
        "source": "阿里云智能校招专场",
        "announcement_text": "全球领先的数字商业与云计算基础设施。通义实验室与智算核心全面招聘，提供全球顶级计算集群实战与科学家带教。"
    },
    {
        "company_name": "阿里巴巴集团 (Alibaba)",
        "industry": "互联网/IT",
        "recruitment_type": "秋招正式批 (电商核心研发与智能算法)",
        "target_graduates": "2026/2027届",
        "roles_summary": "淘宝天猫智能搜索推荐算法、高并发电商交易系统架构、前端跨端工程、核心供应链运筹优化、数字营销管培生 (地点: 杭州/北京/上海)",
        "apply_url": "https://talent.alibaba.com/campus",
        "referral_code": "ALI_CAMPUS2026",
        "start_date": "2026-08-28",
        "deadline": "2026-10-31",
        "status": "hot",
        "source": "淘天集团校园招聘",
        "announcement_text": "万亿级电商核心业务，服务数亿消费者与千万商家，提供顶格工程挑战与跨业务体系轮岗机会。"
    },
    {
        "company_name": "字节跳动 (ByteDance)",
        "industry": "互联网/IT",
        "recruitment_type": "秋招正式批 (核心算法与通用大模型专项)",
        "target_graduates": "2026/2027届",
        "roles_summary": "豆包通用大模型预训练/RLHF、抖音多模态推荐算法、机器视觉与语音交互、智能搜索、强化学习研究员 (地点: 北京/上海/深圳/杭州/新加坡)",
        "apply_url": "https://job.bytedance.com/campus",
        "referral_code": "BYTE_CAREER_26",
        "start_date": "2026-08-20",
        "deadline": "2026-10-31",
        "status": "hot",
        "source": "字节跳动 AI Lab & 推荐算法团队",
        "announcement_text": "全球顶尖信息流与通用人工智能领跑者。豆包大模型与核心算法团队直招，极客扁平文化，提供业内高规格校招薪酬及顶配算力支持。"
    },
    {
        "company_name": "字节跳动 (ByteDance)",
        "industry": "互联网/IT",
        "recruitment_type": "秋招正式批 (工程研发与系统架构专场)",
        "target_graduates": "2026/2027届",
        "roles_summary": "后端开发工程师(Go/Python)、前端与跨端开发、Android/iOS客户端研发、火山引擎云原生架构、超海量大数据计算引擎 (地点: 北京/上海/深圳/杭州/成都/武汉)",
        "apply_url": "https://job.bytedance.com/campus",
        "referral_code": "BYTE_CAREER_26",
        "start_date": "2026-08-20",
        "deadline": "2026-10-31",
        "status": "hot",
        "source": "字节跳动基础架构与工程研发中心",
        "announcement_text": "支撑数十亿级用户全球高并发访问的底层基础设施。务实扁平，提供全额五险一金、每日三餐及高额就近租房补贴。"
    },
    {
        "company_name": "美团 (Meituan)",
        "industry": "互联网/IT",
        "recruitment_type": "秋招正式批",
        "target_graduates": "2026/2027届",
        "roles_summary": "即时配送超大规模超图运筹优化算法、无人机/自动配送车自动驾驶、本地生活高并发系统、到店到家技术 (地点: 北京/上海/成都/深圳)",
        "apply_url": "https://zhaopin.meituan.com/web/campus",
        "referral_code": "MEITUAN_AUTO26",
        "start_date": "2026-08-22",
        "deadline": "2026-10-31",
        "status": "hot",
        "source": "美团招聘官网",
        "announcement_text": "科技连接人与生活服务的领军企业。运筹优化与无人配送技术走在行业前列，设立美团大学系统化工程师成长体系。"
    },
    {
        "company_name": "米哈游 (miHoYo)",
        "industry": "互联网/IT",
        "recruitment_type": "秋招正式批",
        "target_graduates": "2026/2027届",
        "roles_summary": "自研二次元游戏引擎底层、图形学渲染研究员、关卡与战斗数值设计、角色概念美术、海外本地化运营 (地点: 上海/新加坡)",
        "apply_url": "https://jobs.mihoyo.com/campus",
        "referral_code": "MHY_GAME2026",
        "start_date": "2026-08-25",
        "deadline": "2026-10-25",
        "status": "hot",
        "source": "米哈游招聘系统",
        "announcement_text": "全球顶尖头部游戏研运商。技术宅拯救世界，倡导极客与艺术并重，提供行业顶格薪酬与全员高规格年度激励。"
    },

    # ==================== 6. 消费品 / 智能家电 / 综合龙头 ====================
    {
        "company_name": "美的集团 (Midea)",
        "industry": "综合商贸/消费制造",
        "recruitment_type": "秋招正式批",
        "target_graduates": "2026/2027届",
        "roles_summary": "智能家居物联网AI系统、库卡工业机器人控制、电力电子研发、全球供应链管理、海外市场管培生 (地点: 佛山/深圳/上海/合肥)",
        "apply_url": "https://careers.midea.com/campus",
        "referral_code": "MIDEA_TECH2026",
        "start_date": "2026-09-01",
        "deadline": "2026-11-20",
        "status": "hot",
        "source": "美的集团招聘官网",
        "announcement_text": "世界500强智能科技巨头，业务覆盖智能家居、工业技术、楼宇科技与机器人系统，具备完善的全球化轮岗和安居补贴政策。"
    },
    {
        "company_name": "宝洁中国 (P&G)",
        "industry": "综合商贸/消费制造",
        "recruitment_type": "秋招正式批",
        "target_graduates": "2026/2027届",
        "roles_summary": "品牌全域营销管理(BRM)、全渠道销售与零售、智能供应链与工程、信息技术与数据战略 (地点: 广州/北京/上海)",
        "apply_url": "https://www.pgcareers.com/china",
        "referral_code": "PG_LEAD_2026",
        "start_date": "2026-09-01",
        "deadline": "2026-10-15",
        "status": "hot",
        "source": "宝洁中国招聘门户",
        "announcement_text": "全球快消品黄埔军校。实行第一天即赋予真实业务决策权培养机制，提供国际化跨部门流动机会与顶级管培福利。"
    }
]
