# -*- coding: utf-8 -*-
"""
全国考公考编、定向选调生、事业单位与重点央国企官方真实招录日程权威知识库
涵盖国家公务员局、各省人事考试网、组织部官网、国资委、各大部属医院、高校及重点央国企官方渠道。
"""

from typing import List, Dict, Any

AUTHORITATIVE_PUBLIC_RECRUITS: List[Dict[str, Any]] = [
    # ==================== 1. 公务员 (国考 / 各省省考) ====================
    {
        "title": "中央机关及其直属机构2026年度考试录用公务员 (国考)",
        "organization": "国家公务员局 / 中共中央组织部",
        "category": "公务员(国考/省考)",
        "region": "全国",
        "target_graduates": "2026届应届生及符合条件往届生",
        "roles_summary": "中央直属部委、各省税务局、海关、海事、移民局、统计调查、银保监等行政综合、执法与技术岗位",
        "headcount": "39,600人",
        "apply_start_date": "2026-10-15",
        "apply_end_date": "2026-10-24",
        "exam_date": "2026-11-30",
        "status": "hot",
        "apply_url": "http://subb.scs.gov.cn/pp/gkweb/core/web/ui/business/home/gkhome.html",
        "announcement_url": "http://subb.scs.gov.cn/",
        "announcement_text": "公共科目笔试包括行政职业能力测验和申论两科。海关、税务、铁路公安等部分职位加试专业科目笔试。",
        "source": "国家公务员局专题招考网"
    },
    {
        "title": "北京市2026年度各级机关考试录用公务员 (京考)",
        "organization": "中共北京市委组织部 / 北京市人力资源和社会保障局",
        "category": "公务员(国考/省考)",
        "region": "北京",
        "target_graduates": "2026届普通高校毕业生",
        "roles_summary": "市级机关、各区级机关、街道乡镇及基层行政执法、法学、财会、计算机、规划建设与综合管理岗位",
        "headcount": "4,345人",
        "apply_start_date": "2026-11-18",
        "apply_end_date": "2026-11-22",
        "exam_date": "2026-12-14",
        "status": "hot",
        "apply_url": "http://rsj.beijing.gov.cn/ywsite/bjpta/",
        "announcement_url": "http://rsj.beijing.gov.cn/",
        "announcement_text": "公共科目包括行测和申论。公安机关人民警察职位加试公安专业科目笔试。招考人数向应届生与基层一线倾斜。",
        "source": "北京组工网 / 北京市人事考试网"
    },
    {
        "title": "上海市2026年度考试录用公务员公告 (沪考)",
        "organization": "中共上海市委组织部",
        "category": "公务员(国考/省考)",
        "region": "上海",
        "target_graduates": "2026届应届高校毕业生",
        "roles_summary": "政法、信息技术、财经、城市建设、卫生健康等专业类别公务员及行政执法类职位",
        "headcount": "2,340人",
        "apply_start_date": "2026-11-04",
        "apply_end_date": "2026-11-10",
        "exam_date": "2026-12-07",
        "status": "hot",
        "apply_url": "http://www.shacs.gov.cn/",
        "announcement_url": "http://www.shacs.gov.cn/",
        "announcement_text": "笔试内容包括公共科目（行政职业能力测验和申论）和专业科目。支持应届高校毕业生专项招录。",
        "source": "上海市公务员局官网"
    },
    {
        "title": "广东省2026年考试录用公务员公告 (粤考四级联考)",
        "organization": "中共广东省委组织部 / 广东省人力资源和社会保障厅",
        "category": "公务员(国考/省考)",
        "region": "广东",
        "target_graduates": "2026届应届高校毕业生及往届生",
        "roles_summary": "省直机关、珠三角九市、粤东粤西粤北基层机关、公安司法、生态环境、财政金融与数字化改革岗位",
        "headcount": "17,300人",
        "apply_start_date": "2027-01-16",
        "apply_end_date": "2027-01-22",
        "exam_date": "2027-03-08",
        "status": "hot",
        "apply_url": "https://ggfw.hrss.gd.gov.cn/gwyks/",
        "announcement_url": "https://www.gzzk.gov.cn/",
        "announcement_text": "全省统一组织公共科目笔试。加大对高校毕业生招录支持力度，珠三角核心区与粤东西北基层职位广阔。",
        "source": "广东组织工作网 / 广东省人事考试网"
    },
    {
        "title": "江苏省2026年度考试录用公务员公告",
        "organization": "中共江苏省委组织部",
        "category": "公务员(国考/省考)",
        "region": "江苏",
        "target_graduates": "2026年应届高校毕业生",
        "roles_summary": "省市县乡四级机关编制，包含法律、经济、计算机软硬件、城乡建设、社会管理等专业类职位",
        "headcount": "9,470人",
        "apply_start_date": "2026-11-08",
        "apply_end_date": "2026-11-14",
        "exam_date": "2026-12-08",
        "status": "hot",
        "apply_url": "http://jshrss.jiangsu.gov.cn/",
        "announcement_url": "http://www.jszzb.gov.cn/",
        "announcement_text": "公共科目按A、B、C三类职位分别命题，A类为综合管理，B类为行政执法，C类为乡镇基层。",
        "source": "江苏省人事考试网"
    },
    {
        "title": "浙江省2026年各级机关单位考试录用公务员公告",
        "organization": "中共浙江省委组织部",
        "category": "公务员(国考/省考)",
        "region": "浙江",
        "target_graduates": "2026届高校应届毕业生",
        "roles_summary": "高质量发展建设共同富裕示范区专项岗位、数字政府与智慧治理、行政执法与乡镇综合管理",
        "headcount": "7,180人",
        "apply_start_date": "2026-11-06",
        "apply_end_date": "2026-11-11",
        "exam_date": "2026-12-08",
        "status": "hot",
        "apply_url": "http://gwy.zjks.gov.cn/",
        "announcement_url": "http://www.zjks.gov.cn/",
        "announcement_text": "笔试科目为行测与申论。紧缺职位加试专业素质测试。全省各级机关提供丰富的应届生专属岗位。",
        "source": "浙江省公务员考试录用网"
    },
    {
        "title": "山东省2026年度各级机关招录公务员公告",
        "organization": "中共山东省委组织部",
        "category": "公务员(国考/省考)",
        "region": "山东",
        "target_graduates": "国内普通高等学历教育2026年应届毕业生",
        "roles_summary": "机关综合、财政审计、法检两院、公安特警、农业农村与自然资源规划管理岗位",
        "headcount": "9,600人",
        "apply_start_date": "2026-11-10",
        "apply_end_date": "2026-11-16",
        "exam_date": "2026-12-08",
        "status": "hot",
        "apply_url": "http://www.dtdj.gov.cn/",
        "announcement_url": "http://hrss.shandong.gov.cn/",
        "announcement_text": "笔试统一进行，包括行政职业能力测验和申论。报考公安机关职位的还需参加公安专业科目考试。",
        "source": "灯塔-党建在线 / 山东人事考试信息网"
    },
    {
        "title": "四川省2026年公开考试录用公务员 (四级联考)",
        "organization": "中共四川省委组织部 / 四川省人力资源和社会保障厅",
        "category": "公务员(国考/省考)",
        "region": "四川",
        "target_graduates": "2026年高校应届毕业生及社会人员",
        "roles_summary": "全省各级党政机关、司法行政、综合执法、经济运行与现代产业发展技术岗位",
        "headcount": "8,500人",
        "apply_start_date": "2026-12-05",
        "apply_end_date": "2026-12-11",
        "exam_date": "2027-01-05",
        "status": "hot",
        "apply_url": "http://rst.sc.gov.cn/",
        "announcement_url": "http://www.scpta.com.cn/",
        "announcement_text": "全省统考，包含行测和申论。成都及各市州均有大批编制岗位招录，对应届生设有专项倾斜名额。",
        "source": "四川省人力资源和社会保障厅官网"
    },
    {
        "title": "湖北省2026年度省市县乡考试录用公务员公告",
        "organization": "中共湖北省委组织部",
        "category": "公务员(国考/省考)",
        "region": "湖北",
        "target_graduates": "2026届高校毕业生",
        "roles_summary": "综合管理类、专业技术类、行政执法类职位，涉及工科、理学、经济、法学、医学等各门类",
        "headcount": "6,800人",
        "apply_start_date": "2027-01-15",
        "apply_end_date": "2027-01-21",
        "exam_date": "2027-03-15",
        "status": "hot",
        "apply_url": "http://rst.hubei.gov.cn/",
        "announcement_url": "http://www.hbsrsksy.cn/",
        "announcement_text": "笔试包含行测和申论两门科目。武汉市及各直属机关全面开放网申报名。",
        "source": "湖北省人事考试网"
    },
    {
        "title": "陕西省2026年统一考试录用公务员公告",
        "organization": "中共陕西省委组织部",
        "category": "公务员(国考/省考)",
        "region": "陕西",
        "target_graduates": "2026年应届高校毕业生",
        "roles_summary": "全省党群、政府、法检各级机关综合执法与专业技术岗位",
        "headcount": "5,600人",
        "apply_start_date": "2027-02-01",
        "apply_end_date": "2027-02-07",
        "exam_date": "2027-03-15",
        "status": "hot",
        "apply_url": "http://www.sxrsks.cn/",
        "announcement_url": "http://www.shaanxi.gov.cn/",
        "announcement_text": "笔试科目为行政职业能力测验和申论。西安及关中、陕南、陕北各市县岗位同步开放招录。",
        "source": "陕西省人事考试网"
    },

    # ==================== 2. 定向选调生 ====================
    {
        "title": "2026年中央机关选调应届优秀大学毕业生",
        "organization": "中共中央组织部",
        "category": "选调生",
        "region": "全国",
        "target_graduates": "部分高校2026年全日制应届大学毕业生",
        "roles_summary": "中央办公厅、中组部、发改委、财政部、商务部、外交部等中央直属单位核心机关储备干部",
        "headcount": "1,500人",
        "apply_start_date": "2026-10-15",
        "apply_end_date": "2026-10-25",
        "exam_date": "2026-11-30",
        "status": "hot",
        "apply_url": "http://subb.scs.gov.cn/",
        "announcement_url": "http://subb.scs.gov.cn/",
        "announcement_text": "需经高校党委组织部推荐报考。笔试与国家公务员统一笔试同步举行，政治素养与综合能力要求高。",
        "source": "中央组织部招录专题"
    },
    {
        "title": "广东省2026年度选调优秀大学毕业生 (定向选调)",
        "organization": "中共广东省委组织部",
        "category": "选调生",
        "region": "广东",
        "target_graduates": "国内外重点高校2026年应届大学毕业生",
        "roles_summary": "省直、广州、深圳、珠海、佛山、东莞等珠三角核心市直机关及区县党政领导干部储备",
        "headcount": "2,450人",
        "apply_start_date": "2026-11-20",
        "apply_end_date": "2026-11-26",
        "exam_date": "2026-12-15",
        "status": "hot",
        "apply_url": "https://ggfw.hrss.gd.gov.cn/gwyks/",
        "announcement_url": "https://www.gzzk.gov.cn/",
        "announcement_text": "选调对象包括部分国内高校和国（境）外知名大学应届生。笔试包括《综合行政能力测验》与思维能力考察。",
        "source": "广东组织工作网"
    },
    {
        "title": "北京市2026年度定向选调优秀应届高校毕业生",
        "organization": "中共北京市委组织部",
        "category": "选调生",
        "region": "北京",
        "target_graduates": "双一流重点高校2026年应届本科及硕博毕业生",
        "roles_summary": "北京市级机关、区级机关及重点功能区管委会青年骨干储备，直接对接首善之区核心部门",
        "headcount": "460人",
        "apply_start_date": "2026-10-21",
        "apply_end_date": "2026-10-27",
        "exam_date": "2026-11-17",
        "status": "hot",
        "apply_url": "http://rsj.beijing.gov.cn/",
        "announcement_url": "http://www.bjdj.gov.cn/",
        "announcement_text": "选调职位包括市直部门与各区直部门。笔试包括综合能力测试。入职后统筹安排基层锻炼培养。",
        "source": "北京组工网"
    },
    {
        "title": "上海市2026年度专项选调应届优秀大学毕业生",
        "organization": "中共上海市委组织部",
        "category": "选调生",
        "region": "上海",
        "target_graduates": "重点高校2026届应届本科及研究生",
        "roles_summary": "上海市级机关、各区党政机关骨干岗位，聚焦金融、科技创新、航运与城市精细化治理",
        "headcount": "600人",
        "apply_start_date": "2026-10-09",
        "apply_end_date": "2026-10-23",
        "exam_date": "2026-11-03",
        "status": "hot",
        "apply_url": "http://www.shacs.gov.cn/",
        "announcement_url": "http://www.shacs.gov.cn/",
        "announcement_text": "专项选调采取个人申请、学校推荐、笔试面试、考察体检等程序。提供全面的住房保障与培养计划。",
        "source": "上海市公务员局官网"
    },
    {
        "title": "江苏省2026年应届优秀大学毕业生选调 (名校优生选调)",
        "organization": "中共江苏省委组织部",
        "category": "选调生",
        "region": "江苏",
        "target_graduates": "全国重点高校2026届应届优秀毕业生",
        "roles_summary": "省直机关紧缺专业选调、南京/苏州/无锡各设区市县优秀干部储备计划",
        "headcount": "1,200人",
        "apply_start_date": "2026-10-18",
        "apply_end_date": "2026-10-25",
        "exam_date": "2026-11-17",
        "status": "hot",
        "apply_url": "http://jshrss.jiangsu.gov.cn/",
        "announcement_url": "http://www.jszzb.gov.cn/",
        "announcement_text": "设省直选调、设区市选调和县企专项选调。笔试采用专门命题，重点考查政策理论与解决实际问题能力。",
        "source": "江苏省人事考试网"
    },
    {
        "title": "浙江省2026年度党政机关选调应届优秀大学毕业生",
        "organization": "中共浙江省委组织部",
        "category": "选调生",
        "region": "浙江",
        "target_graduates": "清华、北大等全国高水平大学2026届毕业生",
        "roles_summary": "省直、杭州、宁波等全省各市县党政机关紧缺专业人才专项培育工程",
        "headcount": "1,010人",
        "apply_start_date": "2026-10-08",
        "apply_end_date": "2026-10-20",
        "exam_date": "2026-11-10",
        "status": "hot",
        "apply_url": "http://gwy.zjks.gov.cn/",
        "announcement_url": "http://www.zjks.gov.cn/",
        "announcement_text": "选调生作为后备干部重点培养，考核合格后享受相应职级待遇，并在落户、人才补贴等方面给予倾斜。",
        "source": "浙江省公务员录用网"
    },
    {
        "title": "山东省2026年度选拔录用选调生 (常规及定向选调)",
        "organization": "中共山东省委组织部",
        "category": "选调生",
        "region": "山东",
        "target_graduates": "重点高校2026届全日制应届毕业生",
        "roles_summary": "全省各级党政机关、省属园区及济南、青岛等重点地市年轻骨干培养工程",
        "headcount": "1,680人",
        "apply_start_date": "2026-10-15",
        "apply_end_date": "2026-10-22",
        "exam_date": "2026-11-17",
        "status": "hot",
        "apply_url": "http://www.dtdj.gov.cn/",
        "announcement_url": "http://www.dtdj.gov.cn/",
        "announcement_text": "分高校进行定向报名推荐。笔试分为行政职业能力测验和申论，综合考核择优录取。",
        "source": "灯塔-党建在线"
    },
    {
        "title": "四川省2026届急需紧缺专业选调生招录公告",
        "organization": "中共四川省委组织部",
        "category": "选调生",
        "region": "四川",
        "target_graduates": "国内急需紧缺专业重点高校2026年毕业生",
        "roles_summary": "成都市直机关、天府新区、高新区及全省各市州紧缺技术与综合管理选调",
        "headcount": "2,150人",
        "apply_start_date": "2026-10-10",
        "apply_end_date": "2026-10-21",
        "exam_date": "2026-11-09",
        "status": "hot",
        "apply_url": "http://rst.sc.gov.cn/",
        "announcement_url": "http://www.scpta.com.cn/",
        "announcement_text": "涵盖电子信息、装备制造、现代金融、生物医药、规划建设等急需紧缺专业大类。",
        "source": "四川人事考试网"
    },

    # ==================== 3. 事业单位 (公立医院 / 高校 / 科研院所) ====================
    {
        "title": "中国科学院直属各院所2026年度特别研究助理与事业编招聘",
        "organization": "中国科学院直属院所系统",
        "category": "事业单位",
        "region": "全国",
        "target_graduates": "国内外知名高校2026届硕博毕业生",
        "roles_summary": "物理、化学、计算所、微电子、自动化、生物物理、空间科学等各院所科研与工程技术事业编制",
        "headcount": "3,500人",
        "apply_start_date": "2026-09-01",
        "apply_end_date": "2026-06-30",
        "exam_date": "2026-12-20",
        "status": "hot",
        "apply_url": "https://www.cas.cn/rc/",
        "announcement_url": "https://www.cas.cn/",
        "announcement_text": "提供国家战略科技力量平台支持，解决北京/上海/广州及各分院属地落户与科研启动经费。",
        "source": "中国科学院官网招聘专区"
    },
    {
        "title": "北京协和医院2026年度公开招聘公告 (卫生医疗事业编)",
        "organization": "中国医学科学院北京协和医院",
        "category": "事业单位",
        "region": "北京",
        "target_graduates": "2026届全日制普通高等医学院校毕业生",
        "roles_summary": "内科、外科、妇产、儿科、放射检验、药剂及临床医学转化科研人员与住院医师规培岗位",
        "headcount": "450人",
        "apply_start_date": "2026-10-15",
        "apply_end_date": "2026-11-15",
        "exam_date": "2026-11-25",
        "status": "hot",
        "apply_url": "https://jobs.pumch.cn/",
        "announcement_url": "https://jobs.pumch.cn/",
        "announcement_text": "国家卫生健康委直属三甲医院。录用人员按国家和医院相关规定办理事业单位编制与进京户口手续。",
        "source": "北京协和医院招聘官网"
    },
    {
        "title": "四川大学华西医院2026年公开招聘公告 (医疗科研事业单位)",
        "organization": "四川大学华西医院 / 华西临床医学院",
        "category": "事业单位",
        "region": "四川",
        "target_graduates": "国内外医科名校2026届硕博研究生",
        "roles_summary": "临床医学、麻醉重症、影像超声、基础医学、医学人工智能及生物医药交叉学科高端人才",
        "headcount": "680人",
        "apply_start_date": "2026-10-20",
        "apply_end_date": "2026-11-20",
        "exam_date": "2026-12-05",
        "status": "hot",
        "apply_url": "http://www.wchscu.cn/public/index.html",
        "announcement_url": "http://www.wchscu.cn/",
        "announcement_text": "全国综合排名前列医院，提供国家重点实验室支撑、优厚薪资待遇与科研启动配套。",
        "source": "四川大学华西医院官网"
    },
    {
        "title": "中山大学附属第一医院2026年医疗科研与医技岗位招聘",
        "organization": "中山大学附属第一医院 (中山一院)",
        "category": "事业单位",
        "region": "广东",
        "target_graduates": "2026届普通高校医学及相关专业毕业生",
        "roles_summary": "临床医师、专职科研人员、博士后研究员、药学部、医学检验部与医学影像科",
        "headcount": "520人",
        "apply_start_date": "2026-09-01",
        "apply_end_date": "2026-09-19",
        "exam_date": "2026-09-26",
        "status": "ending",
        "apply_url": "http://www.fahsysu.org.cn/",
        "announcement_url": "http://www.fahsysu.org.cn/",
        "announcement_text": "广东省高水平医院、国家医学中心创建单位。提供事业编制待遇、高水平科研平台与广州落户指标。",
        "source": "中山大学附属第一医院官方招聘系统"
    },
    {
        "title": "清华大学2026年度管理支撑、实验技术与教辅岗位公开招聘",
        "organization": "清华大学人事处",
        "category": "事业单位",
        "region": "北京",
        "target_graduates": "2026届统招统分应届毕业生",
        "roles_summary": "各院系教学科研辅助、重点实验室技术支持、学生辅导员与综合行政事务管理岗位",
        "headcount": "300人",
        "apply_start_date": "2026-10-01",
        "apply_end_date": "2027-03-31",
        "exam_date": "2026-12-10",
        "status": "hot",
        "apply_url": "http://jobs.tsinghua.edu.cn/",
        "announcement_url": "http://jobs.tsinghua.edu.cn/",
        "announcement_text": "享有清华大学优质教育医疗资源，按政策协助办理进京落户，完善的薪酬福利与教职工培养体系。",
        "source": "清华大学招聘网"
    },
    {
        "title": "广东省属及各市事业单位2026年集中公开招聘高校毕业生",
        "organization": "广东省人力资源和社会保障厅",
        "category": "事业单位",
        "region": "广东",
        "target_graduates": "2026届高校毕业生",
        "roles_summary": "全省各级公益一类、二类事业单位，涵盖教育、科技、文化、卫生等综合管理与专业技术职位",
        "headcount": "12,800人",
        "apply_start_date": "2027-03-10",
        "apply_end_date": "2027-03-16",
        "exam_date": "2027-04-18",
        "status": "hot",
        "apply_url": "http://hrss.gd.gov.cn/",
        "announcement_url": "http://hrss.gd.gov.cn/",
        "announcement_text": "全省统一统考笔试《基本能力测试》，珠三角各市及粤东粤西粤北事业单位岗位集中开放招募。",
        "source": "广东省人力资源和社会保障厅人事考试专栏"
    },
    {
        "title": "江苏省属事业单位2026年统一公开招聘人员公告",
        "organization": "江苏省人力资源和社会保障厅",
        "category": "事业单位",
        "region": "江苏",
        "target_graduates": "2026届应届毕业生及往届人员",
        "roles_summary": "省直高校、科研院所、各直属厅局事业单位管理类岗位、通用类专业技术岗位",
        "headcount": "4,500人",
        "apply_start_date": "2027-02-15",
        "apply_end_date": "2027-02-21",
        "exam_date": "2027-03-29",
        "status": "hot",
        "apply_url": "http://jshrss.jiangsu.gov.cn/",
        "announcement_url": "http://jshrss.jiangsu.gov.cn/",
        "announcement_text": "统一笔试科目为综合知识和专业素质，省直各单位严格规范聘用程序，按事业编制录用。",
        "source": "江苏省人事考试网"
    },

    # ==================== 4. 央企 / 重点国企 ====================
    {
        "title": "国家电网有限公司2026年高校毕业生招聘 (统考批次)",
        "organization": "国家电网有限公司 (State Grid)",
        "category": "央企国企",
        "region": "全国",
        "target_graduates": "2026届电工类、计算机类、通信类、财会类及相关专业应届生",
        "roles_summary": "27个省网电力公司、电科院、南瑞集团、智芯微电子及各直属机构工程建设、电网调控与数字化研发",
        "headcount": "18,500人",
        "apply_start_date": "2026-11-01",
        "apply_end_date": "2026-11-20",
        "exam_date": "2026-12-08",
        "status": "hot",
        "apply_url": "https://zhaopin.sgcc.com.cn/",
        "announcement_url": "https://zhaopin.sgcc.com.cn/",
        "announcement_text": "全国统一组织笔试，按电工类、计算机类、通信类、财管类等专业分卷命题。世界500强前列央企待遇保障。",
        "source": "国家电网有限公司人力资源招聘平台"
    },
    {
        "title": "中国南方电网有限责任公司2026年校园招聘公告",
        "organization": "中国南方电网有限责任公司 (CSG)",
        "category": "央企国企",
        "region": "广东",
        "target_graduates": "2026届普通高校大学毕业生",
        "roles_summary": "广东、广西、云南、贵州、海南电网公司、鼎元资产、南网数研院电气、信息、自动化与运营岗位",
        "headcount": "6,500人",
        "apply_start_date": "2026-10-18",
        "apply_end_date": "2026-11-15",
        "exam_date": "2026-12-01",
        "status": "hot",
        "apply_url": "http://zhaopin.csg.cn/",
        "announcement_url": "http://zhaopin.csg.cn/",
        "announcement_text": "统一笔试在线进行，包含专业知识与综合素质测试。珠三角电网岗位具有极高吸引力。",
        "source": "中国南方电网员工招聘系统"
    },
    {
        "title": "中国移动通信集团有限公司2026届秋季全网校园招聘",
        "organization": "中国移动通信集团有限公司 (China Mobile)",
        "category": "央企国企",
        "region": "全国",
        "target_graduates": "2026届国内外高校毕业生",
        "roles_summary": "总部直属机构、31省移动公司、咪咕、中移动研究院通信网络、云计算、AI大模型、软件开发与数智市场",
        "headcount": "15,000人",
        "apply_start_date": "2026-09-01",
        "apply_end_date": "2026-10-20",
        "exam_date": "2026-10-26",
        "status": "hot",
        "apply_url": "https://job.10086.cn/",
        "announcement_url": "https://job.10086.cn/",
        "announcement_text": "全国统一上机笔试，涵盖行业领先的5G、算力网络研发职位，提供六险二金及全套央企福利保障。",
        "source": "中国移动招聘官网"
    },
    {
        "title": "中国电信集团有限公司2026年度秋季校园招聘",
        "organization": "中国电信集团有限公司 (China Telecom)",
        "category": "央企国企",
        "region": "全国",
        "target_graduates": "2026届应届高校毕业生",
        "roles_summary": "天翼云、研究院、各省分公司云网融合、量子安全、大数据AI工程与全光网络建设",
        "headcount": "12,000人",
        "apply_start_date": "2026-08-25",
        "apply_end_date": "2026-10-25",
        "exam_date": "2026-11-02",
        "status": "hot",
        "apply_url": "http://job.chinatelecom.com.cn/",
        "announcement_url": "http://job.chinatelecom.com.cn/",
        "announcement_text": "全国统一秋招网申入口，提供科技创新人才专项通道与极具竞争力的央企薪资待遇。",
        "source": "中国电信校园招聘官网"
    },
    {
        "title": "中国联合网络通信集团 (中国联通) 2026届校园招聘",
        "organization": "中国联合网络通信集团有限公司 (China Unicom)",
        "category": "央企国企",
        "region": "全国",
        "target_graduates": "2026届高校毕业生",
        "roles_summary": "联通数科、联通研究院、各省市分公司软件研发、网络运维、数据智能与政企解决方案",
        "headcount": "10,000人",
        "apply_start_date": "2026-09-05",
        "apply_end_date": "2026-10-31",
        "exam_date": "2026-11-09",
        "status": "hot",
        "apply_url": "http://chinaunicom.zhaopin.com/",
        "announcement_url": "http://chinaunicom.zhaopin.com/",
        "announcement_text": "大力招募网络信息安全、人工智能与产业互联网复合型人才，享有体系化央企培养与导师带教。",
        "source": "中国联通人才招聘平台"
    },
    {
        "title": "中国烟草总公司及各省中烟工业2026年高校毕业生招聘",
        "organization": "中国烟草总公司 / 烟草专卖局及各省中烟",
        "category": "央企国企",
        "region": "全国",
        "target_graduates": "2026届大学本科及以上学历毕业生",
        "roles_summary": "烟草专卖执法、卷烟制造工艺、电气机械自动化、计算机信息技术、财务审计与综合行政管理",
        "headcount": "4,800人",
        "apply_start_date": "2026-11-01",
        "apply_end_date": "2027-04-30",
        "exam_date": "2026-12-15",
        "status": "hot",
        "apply_url": "http://www.tobacco.gov.cn/",
        "announcement_url": "http://www.tobacco.gov.cn/",
        "announcement_text": "各省烟草专卖局及中烟工业公司自主发布具体岗位简章，享有极高薪酬竞争力、六险二金与长期职业稳定度。",
        "source": "国家烟草专卖局政府网站招考信息"
    },
    {
        "title": "中国建筑集团有限公司 (中建各工程局) 2026届校园招聘",
        "organization": "中国建筑集团有限公司 (CSCEC)",
        "category": "央企国企",
        "region": "全国",
        "target_graduates": "2026届土木、建筑、电气、暖通、机械、计算机及经管毕业生",
        "roles_summary": "中建一局至八局、中建设计、海外事业部工程技术、项目管理、数字化建造与商务法务",
        "headcount": "20,000人",
        "apply_start_date": "2026-09-01",
        "apply_end_date": "2026-05-30",
        "exam_date": "2026-10-25",
        "status": "hot",
        "apply_url": "https://job.cscec.com/",
        "announcement_url": "https://job.cscec.com/",
        "announcement_text": "全球最大的投资建设集团。组织全国统一测评，包含知觉测试与职业性格测评，合格后各工程局直录。",
        "source": "中国建筑招聘管理系统"
    },
    {
        "title": "中国铁道建筑集团 (中国铁建) 2026届校园招聘公告",
        "organization": "中国铁道建筑集团有限公司 (CRCC)",
        "category": "央企国企",
        "region": "全国",
        "target_graduates": "2026届高校毕业生",
        "roles_summary": "各工程局、设计院桥隧工程、轨道交通、电气化、智慧交通与运营维护管理",
        "headcount": "12,000人",
        "apply_start_date": "2026-09-01",
        "apply_end_date": "2026-09-20",
        "exam_date": "2026-09-28",
        "status": "ending",
        "apply_url": "http://crcc.zhiye.com/",
        "announcement_url": "http://www.crcc.cn/",
        "announcement_text": "特大型中央企业，覆盖高铁、地铁、特大桥隧全产业链，解决多地落户与年金保障。",
        "source": "中国铁建校园招聘官网"
    },
    {
        "title": "中国核工业集团有限公司 (中核集团) 2026届校园招聘",
        "organization": "中国核工业集团有限公司 (CNNC)",
        "category": "央企国企",
        "region": "全国",
        "target_graduates": "2026届理工科及经管文博应届毕业生",
        "roles_summary": "核科学与技术、核能工程、热能动力、机械制造、控制工程、软件开发与国防科研骨干岗位",
        "headcount": "5,000人",
        "apply_start_date": "2026-09-15",
        "apply_end_date": "2026-11-30",
        "exam_date": "2026-12-05",
        "status": "hot",
        "apply_url": "http://cnnc.zhaopin.com/",
        "announcement_url": "http://www.cnnc.com.cn/",
        "announcement_text": "国家安全战略基石央企，承担重大科研攻关项目，提供事业发展快车道与优渥人才补贴。",
        "source": "中核集团招聘系统"
    },
    {
        "title": "中国航空工业集团有限公司 (航空工业) 2026校招",
        "organization": "中国航空工业集团有限公司 (AVIC)",
        "category": "央企国企",
        "region": "全国",
        "target_graduates": "2026届航空宇航、力学、电气、控制、材料与软件算法硕博",
        "roles_summary": "战机、大飞机、直升机、机载雷达与航空智能制造研究所与制造基地研发工程师",
        "headcount": "6,000人",
        "apply_start_date": "2026-09-10",
        "apply_end_date": "2026-12-10",
        "exam_date": "2026-11-20",
        "status": "hot",
        "apply_url": "http://avic.zhaopin.com/",
        "announcement_url": "http://www.avic.com.cn/",
        "announcement_text": "国防军工特大型央企，提供解决北京、上海、成都、沈阳、西安等核心城市落户名额与高额安家费。",
        "source": "航空工业招聘专区"
    },
    {
        "title": "中国石油天然气集团 (中石油) 2026届高校毕业生招聘",
        "organization": "中国石油天然气集团有限公司 (CNPC)",
        "category": "央企国企",
        "region": "全国",
        "target_graduates": "2026届应届大学毕业生",
        "roles_summary": "勘探开发、油气储运、炼油化工、新能源研发、财务与数字化信息技术岗位",
        "headcount": "8,000人",
        "apply_start_date": "2026-09-05",
        "apply_end_date": "2026-10-25",
        "exam_date": "2026-11-02",
        "status": "hot",
        "apply_url": "https://zhaopin.cnpc.com.cn/",
        "announcement_url": "https://zhaopin.cnpc.com.cn/",
        "announcement_text": "统一准入考试，考核思想潜质与通用能力。世界500强央企，薪酬福利规范，六险二金全覆盖。",
        "source": "中石油高校毕业生招聘平台"
    },
    {
        "title": "中国石油化工集团 (中石化) 2026年度毕业生招聘",
        "organization": "中国石油化工集团有限公司 (Sinopec)",
        "category": "央企国企",
        "region": "全国",
        "target_graduates": "2026届全国高校应届毕业生",
        "roles_summary": "石油工程、化工工艺、材料科学、安全环保、机械电气、计算机算法与国际贸易",
        "headcount": "7,500人",
        "apply_start_date": "2026-09-10",
        "apply_end_date": "2026-11-03",
        "exam_date": "2026-11-17",
        "status": "hot",
        "apply_url": "http://job.sinopec.com/",
        "announcement_url": "http://job.sinopec.com/",
        "announcement_text": "全国统一初选考试（上机），直属各油田、石化分公司与工程研究院按专业综合考录。",
        "source": "中国石化人才招聘网"
    },
    {
        "title": "中国海洋石油集团 (中海油) 2026届高校毕业生招聘",
        "organization": "中国海洋石油集团有限公司 (CNOOC)",
        "category": "央企国企",
        "region": "全国",
        "target_graduates": "2026届普通高校毕业生",
        "roles_summary": "海洋工程、深海钻探、地质勘探、新能源技术、财务资产与信息化技术工程师",
        "headcount": "3,600人",
        "apply_start_date": "2026-09-08",
        "apply_end_date": "2026-11-10",
        "exam_date": "2026-11-23",
        "status": "hot",
        "apply_url": "https://cnooc.zhaopin.com/",
        "announcement_url": "https://www.cnooc.com.cn/",
        "announcement_text": "海洋能源国家队，拥有广阔的深海科研平台与完备的薪酬关怀福利机制。",
        "source": "中海油招聘平台"
    },
    {
        "title": "中国工商银行2026年度秋季校园招聘公告",
        "organization": "中国工商银行 (ICBC)",
        "category": "央企国企",
        "region": "全国",
        "target_graduates": "2026届应届本科、硕士及博士研究生",
        "roles_summary": "总行本部、软件开发中心、数据中心、各省市分行科技菁英、业务管培与专业金融客户经理",
        "headcount": "19,000人",
        "apply_start_date": "2026-09-01",
        "apply_end_date": "2026-10-15",
        "exam_date": "2026-10-28",
        "status": "hot",
        "apply_url": "https://job.icbc.com.cn/",
        "announcement_url": "https://job.icbc.com.cn/",
        "announcement_text": "“宇宙行”统一上机笔试。科技菁英类岗位直招计算机、数据科学与金融工程专业人才。",
        "source": "中国工商银行人才招聘官网"
    },
    {
        "title": "中国建设银行2026年度秋季校园招聘公告",
        "organization": "中国建设银行 (CCB)",
        "category": "央企国企",
        "region": "全国",
        "target_graduates": "2026届境内外高等院校毕业生",
        "roles_summary": "总行直属机构、建信金科、各分行金融科技岗、管理培训生、综合业务与信贷风控",
        "headcount": "16,000人",
        "apply_start_date": "2026-09-05",
        "apply_end_date": "2026-10-18",
        "exam_date": "2026-10-30",
        "status": "hot",
        "apply_url": "http://job.ccb.com/",
        "announcement_url": "http://job.ccb.com/",
        "announcement_text": "国有大型商业银行统考，提供规范的晋升序列与系统化的金融科技管培生培养体系。",
        "source": "中国建设银行官方招募平台"
    },
    {
        "title": "中国农业银行2026年度秋季校园招聘公告",
        "organization": "中国农业银行 (ABC)",
        "category": "央企国企",
        "region": "全国",
        "target_graduates": "2026届本科及以上应届毕业生",
        "roles_summary": "总行研发中心、数据中心、各省分行数字化金融、绿色金融与综合服务营销岗位",
        "headcount": "18,000人",
        "apply_start_date": "2026-09-03",
        "apply_end_date": "2026-10-16",
        "exam_date": "2026-10-29",
        "status": "hot",
        "apply_url": "https://career.abchina.com.cn/",
        "announcement_url": "https://career.abchina.com.cn/",
        "announcement_text": "全国统一在线机考，涵盖通用就业素质测验EPI、综合知识与英语测试。",
        "source": "中国农业银行人才招聘系统"
    },
    {
        "title": "中国银行2026年全球校园招聘公告",
        "organization": "中国银行 (Bank of China)",
        "category": "央企国企",
        "region": "全国",
        "target_graduates": "2026届境内外院校应届毕业生",
        "roles_summary": "总行、软件中心、各省市分行信息科技、综合管理、跨境金融服务与柜面业务",
        "headcount": "13,000人",
        "apply_start_date": "2026-09-02",
        "apply_end_date": "2026-10-14",
        "exam_date": "2026-10-27",
        "status": "hot",
        "apply_url": "https://campus.chinahr.com/pages/boc2026/",
        "announcement_url": "https://www.boc.cn/",
        "announcement_text": "国际化程度最高的中资大型商业银行，提供涉外金融实践与科技金融专属赛道。",
        "source": "中国银行全球校园招聘平台"
    },
    {
        "title": "交通银行2026届秋季校园招聘公告",
        "organization": "交通银行 (Bank of Communications)",
        "category": "央企国企",
        "region": "全国",
        "target_graduates": "2026届应届高校毕业生",
        "roles_summary": "总行交银金科、软件开发中心、境内省直分行金融科技人员、管培生与客户经理",
        "headcount": "7,500人",
        "apply_start_date": "2026-09-06",
        "apply_end_date": "2026-10-20",
        "exam_date": "2026-11-03",
        "status": "hot",
        "apply_url": "https://job.bankcomm.com/",
        "announcement_url": "https://job.bankcomm.com/",
        "announcement_text": "百年民族金融品牌，总部位于上海，提供完备的六险二金与职业成长双通道发展机制。",
        "source": "交通银行人才招聘官网"
    },
    {
        "title": "中国邮政储蓄银行2026年度校园招聘公告",
        "organization": "中国邮政储蓄银行 (PSBC)",
        "category": "央企国企",
        "region": "全国",
        "target_graduates": "2026届高校毕业生",
        "roles_summary": "总行直属软件研发中心、36家一级分行IT技术工程师、普惠金融专业人才与运营支持",
        "headcount": "8,200人",
        "apply_start_date": "2026-09-10",
        "apply_end_date": "2026-10-22",
        "exam_date": "2026-11-05",
        "status": "hot",
        "apply_url": "http://psbc2026.zhaopin.com/",
        "announcement_url": "http://www.psbc.com/",
        "announcement_text": "网点覆盖面广、成长性好的国有大行，积极吸纳信息科技与经管类青年才俊。",
        "source": "中国邮政储蓄银行招聘专区"
    },
    {
        "title": "招商银行2026届校园招聘公告 (总行及各分行)",
        "organization": "招商银行 (CMB)",
        "category": "央企国企",
        "region": "全国",
        "target_graduates": "2026届全日制普通高等院校毕业生",
        "roles_summary": "总行信息技术研发中心、FinTech数字化精英、各分行管理培训生与零售/批发业务骨干",
        "headcount": "6,000人",
        "apply_start_date": "2026-08-20",
        "apply_end_date": "2026-10-20",
        "exam_date": "2026-10-26",
        "status": "hot",
        "apply_url": "https://career.cmbchina.com/",
        "announcement_url": "https://career.cmbchina.com/",
        "announcement_text": "国内领军股份制商业银行，业界极佳雇主口碑，技术研发实力雄厚，年薪与福利机制优异。",
        "source": "招商银行一网通招募"
    },
    {
        "title": "平安银行2026届校园招聘公告",
        "organization": "平安银行",
        "category": "央企国企",
        "region": "全国",
        "target_graduates": "2026届大学本科及以上毕业生",
        "roles_summary": "总行数字化金融团队、总行IT开发、各分行橙光管培生、投行理财专家与金融分析师",
        "headcount": "4,000人",
        "apply_start_date": "2026-08-28",
        "apply_end_date": "2026-10-25",
        "exam_date": "2026-11-02",
        "status": "hot",
        "apply_url": "https://job.pingan.com/",
        "announcement_url": "https://bank.pingan.com/",
        "announcement_text": "综合金融巨头旗下核心商业银行，以科技引领零售转型，提供高速晋升平台。",
        "source": "平安人才招聘官网"
    },
    {
        "title": "国家能源投资集团有限责任公司 (国家能源集团) 2026届毕业生招聘",
        "organization": "国家能源投资集团有限责任公司",
        "category": "央企国企",
        "region": "全国",
        "target_graduates": "2026届高校毕业生",
        "roles_summary": "煤炭开采、火电光伏风电、煤化工、智慧电网与现代供应链物流工程与综合管理",
        "headcount": "6,800人",
        "apply_start_date": "2026-09-18",
        "apply_end_date": "2026-11-15",
        "exam_date": "2026-11-28",
        "status": "hot",
        "apply_url": "http://zhaopin.chnenergy.com.cn/",
        "announcement_url": "http://zhaopin.chnenergy.com.cn/",
        "announcement_text": "中央直管骨干央企，全球最大的煤炭、火电、风电和煤制油化工公司，待遇福利极具稳定性。",
        "source": "国家能源集团人力资源招聘网站"
    },
    {
        "title": "华润 (集团) 有限公司2026届秋季校园招聘公告",
        "organization": "华润 (集团) 有限公司",
        "category": "央企国企",
        "region": "全国",
        "target_graduates": "2026届国内外高校优秀毕业生",
        "roles_summary": "华润微电子、华润三九医药、华润置地、华润电力、华润燃气技术研发与未来之星管培生",
        "headcount": "8,000人",
        "apply_start_date": "2026-09-01",
        "apply_end_date": "2026-11-30",
        "exam_date": "2026-12-05",
        "status": "hot",
        "apply_url": "https://careers.crh.com.hk/",
        "announcement_url": "https://www.crc.com.cn/",
        "announcement_text": "多元化央企巨头，香港四大中资企业之一，覆盖大消费、综合能源、城市建设、大健康与科技金融。",
        "source": "华润集团官方人才招聘网站"
    }
]
